### ISSUE TITLE
Question: Using the trained CNN

### ISSUE THREAD

**Issue by felixwoestmann** [marcbelmont/cnn-watermark-removal#1]
I just found your repo and tried to use the CNN on a dataset of images, but I ran into a problem.

As described in the README I installed the dependencies with pip, downloaded the training material into the data/ folder and trained the CNN with the given command.

The part I don't understand right now is how I can use the trained CNN for my images.
Hopefully you can help me with that.

**Comment by marcbelmont** [comment]
If you want to test it out with your own images, you use `inference`. Try something like that. 
```
# cat-mask.png is the watermark you add to the image, it should have a transparent background and be relatively close to the training data (for example use color #4d4d4d).
results = inference(session, lambda : dataset_paths(['cat.png']), 0, lambda : dataset_paths(['cat-mask.png'])) 

# if you are in a Jupyter Notebook
show_images(np.concatenate(results, 2)) 
```

**Comment by kubmin** [comment]
Super interesting repo.
I'm having the same problem and I'm quite unsure what to do with the code above. Sorry for being so new here, but is it maybe possible you could help me out with a longer example

**Comment by marcbelmont** [comment]
I've added a command line interface to do inference. See the updated readme.

**Comment by kubmin** [comment]
This is great! Thank you 👍
