### ISSUE TITLE
Add model.ckpt

### ISSUE THREAD

**Issue by iamtodor** [marcbelmont/cnn-watermark-removal#10]
Could you please add model.ckpt that you have trained to avoid personal full dataset training as well?
I assume using this model with transfer learning way: get a pre-trained model, set up training on my own dataset to reach the best result

**Comment by brucewoods** [comment]
im new to tensorflow ,and im also new to python ,  do you guys have quick demo for newers

**Comment by amussey** [comment]
There's a pre-trained dataset available over on #2, if it helps :)

**Comment by aalzooke** [comment]
i'm trying to train to network python3 watermarks.py --logdir=save/ 
but i got the following error, any idea how to solve this problem 
![screenshot from 2018-06-05 15-18-32](https://user-images.githubusercontent.com/14840496/40997824-f5858c68-68d3-11e8-90cd-b0484622112b.png)

**Comment by marcbelmont** [comment]
@aalzooke make sure you have the source images. `data/VOCdevkit/VOC2012/JPEGImages/` should contain images.

**Comment by dragin96** [comment]
![image](https://user-images.githubusercontent.com/23176260/45384229-15700a00-b616-11e8-84fe-5e4b291f758e.png)
@marcbelmont    i have problems, help me fixed python3 watermarks.py --logdir=save/

**Comment by ishandutta2007** [comment]
This post is quite old , has anybody the pretrained model ready now ?
