### ISSUE TITLE
error when try to run  python watermarks.py --image assets/cat.png --selection assets/cat-selection.png

### ISSUE THREAD

**Issue by aalzooke** [marcbelmont/cnn-watermark-removal#12]
I followed your requirement but when i try to run  python watermarks.py --image assets/cat.png --selection assets/cat-selection.png
i got the following error. 
![screenshot from 2018-06-05 16-05-12](https://user-images.githubusercontent.com/14840496/40999957-76183c9e-68da-11e8-9567-6bbfbceffd25.png)

**Comment by marcbelmont** [comment]
@aalzooke which version of Tensorflow are you using? I built this using `tensorflow==1.3.0`. In recent version `Dataset` is not in `contrib`. You can try `tf.data.Dataset...` instead.
