### ISSUE TITLE
what is the function of empty.png?

### ISSUE THREAD

**Issue by LegendFC** [marcbelmont/cnn-watermark-removal#14]
My output.png looks like a part of source image. The source image has a size of 1200*530, and the output image only has a size of 300*300. I find the  size of empty.png is also 300*300. So I wonder what the function of empty.png is.

**Comment by marcbelmont** [comment]
During training, we use a mask to hide parts of the image. And the model has to recover the content that has been masked. During inference, there is no mask. That's why we have use this transparent image.
