### ISSUE TITLE
Where to place training Data?

### ISSUE THREAD

**Issue by Skarlett** [marcbelmont/cnn-watermark-removal#16]
I'm not exactly sure where to place training data, if it should be in a specific format or not.
Error message: `Source images are missing!`

Please document these into the `README.md` file. Its quite stressful to try and find.

**Comment by heliocarbex** [comment]
I think that this code is not updated. At the file dataset.py, we have in line 138:
`def get_images():`
`    data = None`
`    for path in glob('cifar-10-batches-py/data_batch_*'):`

So, this code is expecting a folder named "cifar-10-batches-py" and files matching that string "data_batch_*".
