### ISSUE TITLE
need brief video tutorial link

### ISSUE THREAD

**Issue by xncx** [marcbelmont/cnn-watermark-removal#17]
i am not familiar tensorflow-python, but i'd love to try running this interesting project.

will anyone post steps to run it ( video tutorial would be extremely helpful )

**Comment by xqdd** [comment]
@xncx 
https://github.com/marcbelmont/cnn-watermark-removal#usage

**Comment by kuznetsoffandrey** [comment]
Why we need selection image for inference? Just for speed up?

**Comment by marcbelmont** [comment]
The selection image is needed because it tells the neural net which part of the image needs to be treated. Without selection, it was not working.
