### ISSUE TITLE
how should I create corresponding selection pngs based on my own images?

### ISSUE THREAD

**Issue by muyue1238** [marcbelmont/cnn-watermark-removal#22]
Hi, I ran a problem when trying to test your pre-trained model on my own image, and I'm a little confused by the cat-selection.png. I know that the model can work well when corresponding selection.png is provided. But I noticed that cat.png and cat-selection.png have completely different sizes. How does the model know the corresponding relationship between two images. I tried to change the size of cat-selection.png and the outcome did become worse, so I'm pretty sure that there's something I didn't notice. Can anyone answer my question?

**Comment by marcbelmont** [comment]
https://github.com/marcbelmont/cnn-watermark-removal/blob/master/dataset.py#L47
is what you are looking for. The image and the selection are cropped and resized using `tf.image.resize_image_with_crop_or_pad` before being fed to the network for inference. Not super intuitive. Do you have a pull request to make this cleaner?

**Comment by Edwardmark** [comment]
@marcbelmont so how to create the selection.png?

**Comment by Edwardmark** [comment]
@muyue1238 could you tell me how to create the selection.png?

**Comment by kmrabhay** [comment]
I have different sets of image with different text water mark. Could you please tell how to create the selection?
