### ISSUE TITLE
python watermarks.py --image assets/output.png --selection assets/cat-selection.png?

### ISSUE THREAD

**Issue by FancyXun** [marcbelmont/cnn-watermark-removal#3]
what does the output.png look like when run `python watermarks.py --image assets/output.png --selection assets/cat-selection.png`? my output.png still has the watermark and it looks like a part of source image.

**Comment by marcbelmont** [comment]
The output should look like column 2 of https://github.com/marcbelmont/cnn-watermark-removal/blob/master/assets/example.png . For how many epochs did you train?  Can you share your model weights?

**Comment by FancyXun** [comment]
No reminder to me for your answer...
I can't find my model weights in /tmp. Maybe restarting computer made it deleted? my epochs is 1e5,the source is 1e6,but it is too long for me.Thanks for your reply @marcbelmont

**Comment by marcbelmont** [comment]
Yes, the content of /tmp is removed after a restart. You can use those weights:
https://github.com/marcbelmont/cnn-watermark-removal/files/1594328/data.zip
