### ISSUE TITLE
Little bug reminder

### ISSUE THREAD

**Issue by huhaoranak47** [marcbelmont/cnn-watermark-removal#4]
1 watermarks.py line 12 should be tf.flags.DEFINE_string('logdir', '/log', 'Log directory')
2 you should build an directory named 'data' and put the traindata in that
3 training cost lots of time

**Comment by huhaoranak47** [comment]
4 watermarks.py line 7 should be 
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

**Comment by marcbelmont** [comment]
I would be happy to merge your pull request.

**Comment by huhaoranak47** [comment]
Thanks a lot man
I will be appreciated that if you share the model.ckpt file
it cost almost 2 days to train the model

**Comment by marcbelmont** [comment]
Pretrained weights have been provided in https://github.com/marcbelmont/cnn-watermark-removal/issues/5
