### ISSUE TITLE
Can we run this with GPU?

### ISSUE THREAD

**Issue by navygao** [marcbelmont/cnn-watermark-removal#6]
When I ran this with GPU, its always report following error, any insight?
2018-01-19 11:48:00.339295: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\placer.cc:874] global_step/initial_value: (Const)/job:localhost/replica:0/task:0/device:CPU:0
**2018-01-19 11:48:01.722868: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED**
**2018-01-19 11:48:01.723068: F C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:203] Unexpected Event status: 1**

**Comment by marcbelmont** [comment]
Yes, it can be trained on GPU. Make sure you use the same version of Tensorflow (see requirements.txt file). 
I don't use Windows but it should run there too.
