### ISSUE TITLE
how to generate the mask image in watermarks.py

### ISSUE THREAD

**Issue by prashant0079** [marcbelmont/cnn-watermark-removal#7]
I want to understand that how you were able to generate that image cat-selection.png for predicting output.
Any help will be appreciated.

**Comment by marcbelmont** [comment]
`cat-selection.png` was generated using a simple image editor program. The idea is to draw over the area that needs editing. You don't have to be pixel perfect. The algorithm is trained to find where the watermarks begins.

**Comment by Edwardmark** [comment]
@marcbelmont any code for that?

**Comment by marcbelmont** [comment]
@Edwardmark there is no code for that. The selection is created using an image editor. You take a paintbrush and draw the mask.

**Comment by Edwardmark** [comment]
@marcbelmont so we have to label the mask manully to remove the watermark?

**Comment by marcbelmont** [comment]
@Edwardmark you have to manually highlight the area where the watermark is located. It doesn't have to be pixel perfect.

**Comment by kmrabhay** [comment]
@marcbelmont  Do we have to use same empty selection(with same background) to create the other kinds of selection using image editor?
